# These are supported funding model platforms

github: StrangeOne101 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: StrangeOne101 # Replace with a single Ko-fi username
